//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbook
    {
        public int bookid { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> bookdate { get; set; }
        public string confiramtion { get; set; }
        public string pickup { get; set; }
        public string drop { get; set; }
    }
}
