//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldriverlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbldriverlist()
        {
            this.tbldrivers = new HashSet<tbldriver>();
        }
    
        public int driverid { get; set; }
        public string drivername { get; set; }
        public string type { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> experience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbldriver> tbldrivers { get; set; }
    }
}
