//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldriver
    {
        public int hireid { get; set; }
        public string drivertype { get; set; }
        public Nullable<int> cutomerid { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> driverid { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tbldriverlist tbldriverlist { get; set; }
    }
}
