//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicel
    {
        public int VehicleId { get; set; }
        public string Vehicletype { get; set; }
        public Nullable<int> VehicleNumber { get; set; }
        public Nullable<decimal> vehiclePrice { get; set; }
        public string vehiclePhoto { get; set; }
    }
}
